### ISSUE TITLE
Describe the relationship between the Single Sign On example and WebAuthn

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#23]
There's actually a lot in common between the Single Sign On example and using WebAuthn https://www.w3.org/TR/webauthn/ for sign-on.  Most centrally, both perform sign on using proof of possession of a private key, for instance.

It would be useful to know what advantages this example has over WebAuthn and vice versa.

**Comment by jandrieu** [comment]
Agreed. At TPAC it was discussed that this is probably a separate Note. I initially drafted a section of the use case document to include feature-by-feature comparison of the different technology options available, but I didn't feel I had the background to do so effectively in the time frame of that initial draft.

That said, this is also probably the weakest of the Focal Use Cases in that it doesn't highlight much about DIDs that is unique, especially as you say, relative to WebAuthn.

**Comment by philarcher** [comment]
I've simplified this focal use case a lot to reflect the scope of the WG. The reference to DID-Auth is still there (not WebAuthn) but more or less as 'suggested reading' rather than part of the problem space that the WG is trying to solve. Please review https://w3c.github.io/did-use-cases/#sso and make any further suggestions.

**Comment by philarcher** [comment]
This was addressed back in November. We'll close the issue unless there is further comment.

**Comment by jandrieu** [comment]
+1 to closing
