### ISSUE TITLE
General comment on the document structure

### ISSUE THREAD

**Issue by iherman** [w3c/did-use-cases#26]
(I presume this was the subject of discussions in the CCG days so, maybe, I am just reigniting buried discussions. But I am a new kid on the block...)

I am puzzled by the current structure of the document. It reads like an introduction to DID and some sort of a post-decision justification of why DID are defined. This is not the goal of such a document in my view. According to the charter, what we are supposed to publish is a "use cases and requirements" document (although the title does not say that): what this should mean is to have general requirements (independently of DIDs!) and show that the technology we have chosen does fulfill at least a majority of those requirements. This is not the way the document reads today.

The good news is that, I believe, the information _is_ mostly there, so I am just looking for a reorganization of the document. If I was to reorganize it, here is, roughly, what I would do:

1. A set of use cases. This is, essentially, section 7
2. A number of requirements that can be deduced from the use cases. This is sections 4 & 5 (which are together the focal point of the whole document for me), although I would probably invert the sequence, start with section 5 and summarize it in using the table of section 4 
3. A section on showing how the requirements bind to the use cases, which is, essentially, section 6.

In some sense, we could actually stop there: the fact that DID _does_ fulfill the majority of the requirements, and how, is, logically, a _different_ (albeit necessary!) document. But we can decide to include, in the same document, some sort of a Part II:

1. High level view of DID, essentially section 2
1. More details on what DIDs are; this is section 3, although, if we do publish some sort of a DID Primer, than that may be the better place
2. Showing how DID does respond (or not) to the requirements listed in the required features by showing how those requirements can be mapped, technically, onto a DID-based infrastructure. As far as I can see this is not (_yet?_) part of the current document, and we must, at some point, provide that.

At least for me this would make this document much more useful...

**Comment by iherman** [comment]
Actually, looking at the use cases again, in light of my comments above, the fact that DID terminology is already embedded in the text (e.g., for 7.4 or 7.5) is a problem, too. It just reinforces the fact that the use cases are there to justify DID and not to derive requirements that DID would answer to.

**Comment by philarcher** [comment]
Hi Ivan,

I am 100% in agreement with you on this and have been working with Joe to fix this. You can see the results of my latest edits at https://philarcher.github.io/did-use-cases/. As I usually find, my PR can't be merged automatically so I'll need to do some messing around to make it work but I hope my suggested edits meet with your approval.

I've tried to make sure that the doc does indeed set out the problem and not describe the solution. That said, it would be unhelpful to pretend that a lot of work hasn't already been done and so I think we need a balance between problem statement and "ideas that already exist". I added a section to the effect.

I have removed direct references to work going on/done outside the WG (DID resolution, DID Auth) not because it's not relevant - it clearly is - but because that's out of scope and therefore not something the WG will be addressing. Links to that work persist but they're phrased differently.

**Comment by jandrieu** [comment]
@iherman Do you feel your concerns have been addressed? If not, where can we improve?

**Comment by philarcher** [comment]
This issue was addressed many months ago and should probably have been closed. [Section 1.1](https://w3c.github.io/did-use-cases/#existingWork) explains that the document has not been written *a priori* and overall, the 'solutioneering' has been removed. I propose to close this issue unless there is further comment.

**Comment by jandrieu** [comment]
+1 to closing by 6/24 if no further input. @iherman?

**Comment by iherman** [comment]
My apologies for having missed https://github.com/w3c/did-use-cases/issues/26#issuecomment-638385366. Yes, this can be closed, thanks.

**Comment by jandrieu** [comment]
Thanks, Ivan
