### ISSUE TITLE
Decentralized Identities are simply Credentials and should be defined/called out as such...

### ISSUE THREAD

**Issue by mwherman2000** [w3c/did-use-cases#56]
A Decentralized Identity is simply a Credential and should be defined/called out as such.  That is, a Decentralized Identity is simply a (Verifiable) Credential associated with a Subject by a Decentralized Identifier.  ...a Credential being a collection of Claims (name-value pairs) associated, again, with the Subject by a Decentralized Identifier.

This clarification is important because it leads to a natural partitioning of the actions one performs against a Decentralized Identity in comparison to those actions that are generic to a Credential (e.g. creation) and those that are specific to a Decentralized Identity.

**Comment by TallTed** [comment]
It does not make sense to me to consider any kind of "identity" to be a credential, either verifiable or not.

You say yourself --
> a Decentralized Identity is simply a (Verifiable) Credential associated with a Subject by a Decentralized Identifier

Every element of that sentence is important.

In other words, a Decentralized Identity is not *only* a (Verifiable) Credential -- it is a combination of (at least) three things, *including* a (Verifiable) Credential, a Subject, and a Decentralized Identifier.

My identity may be supported, represented, and/or substantiated by various credentials -- passport, driver's license, birth certificate, etc. -- but none of these *are* my identity.

The "natural partitioning" you are trying to reveal seems rather to be further obscured by the blurring here.

Perhaps it might clarify things if we were to discuss a concrete hypothetical example -- maybe a club membership? -- rather than speaking only of generics.

**Comment by mwherman2000** [comment]
Read https://github.com/w3c/did-use-cases/issues/57#issuecomment-559989122 first.

**Comment by TallTed** [comment]
@mwherman2000 - I have read that. It doesn't change anything I've said.

**Comment by mwherman2000** [comment]
@TallTed I'm curious about any alternatives you have to suggest for the "DID" wording confusion/issues in the use case document?  

This has been an ongoing problem for literally "years" now and the problem still remains ...a situation that I don't believe is acceptable in specification documents.

**Comment by jandrieu** [comment]
Not applicable. Closing.

DIDs are identifiers, which *may* be used as part of an identity system. We do not treat "Decentralized Identities" as credentials.
