### ISSUE TITLE
Use Case Pile-up

### ISSUE THREAD

**Issue by bumblefudge** [w3c/did-use-cases#60]
This is probably a shipment of coals addressed to Newcastle, but the use-case freewrite I did in Barcelona at RWoT well-nigh a year ago never got finalized through the RWoT editorial process, although I did make a slightly more schematic version here:
http://www.caballerojuan.com/assets/static/publishing_chapter_sovrin_book_(graphics_tbd).pdf

If any of the little paragraph-long use cases would be helpful to rework and conform a little more to the format of the rest here, pop me an email or a message through github and I will try to find an hour this week/end to edit it into a proposal to be section 7.6 and another row in the chart in section 6.  Out of curiosity (and I'm still willing to contribute regardless of the answer), are the contributors to this crowdsourced addition to the document listed anywhere, or are they only visible in the git trail?

**Comment by jandrieu** [comment]
@philarcher Let's create issues for each section that might be good source for a PR, then in those issues, suggest language. Then we'll get those into a PR.

**Comment by philarcher** [comment]
I've read through the Self-sovereign identity for digital publication paper and, yes, it has many potential use cases. However, several of them are UCs for Verifiable Credentials rather than DIDs per se. Those that are for DIDs are essentially repeats of the one about anonymous authorship which I have included in PR 86. Hence, I've actually derived just one use case for the the DID UCR
