### ISSUE TITLE
When do we publish a FPWD of the Use Cases document?

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#8]
As described in https://github.com/w3c/did-spec/issues/68#issuecomment-546521745 , our charter https://www.w3.org/2019/09/did-wg-charter.html states that we are producing a Use Cases document defining requirements that the DID specification is intended to meet. Having the Use Cases document is therefore necessary to be able to evaluate the DID specification.

I believe that we should consequently be reviewing and stabilizing the Use Cases document with the same vigor that we are the technical specification, and in the same timeframe.

**Comment by jandrieu** [comment]
Hopefully we should have a draft for FPWD for consideration.

**Comment by brentzundel** [comment]
The WG has committed to publish a FPWD-Note by the end of November 2019

**Comment by burnburn** [comment]
What is the status of this?  Are we saying that the the FPWD cannot be published until all issues marked with the "FPWD" label are resolved?  The latest publication date for November is the 28th, so we would need a WG resolution, latest, by our Tuesday, Nov. 19th call.  What is the plan to resolve these issues by then? @jandrieu @philarcher

**Comment by philarcher** [comment]
We're working on it. As discussed on Tuesday's call, I and others felt it was important to change the angle more towards problem statement rather than a description of the pre-baked solution which is what it was before. The doc today reflects that change as presented to the WG. Joe and I are meeting regularly and working on the doc. I'm confident that I'll have spent more time on it before next week's call and I dare say Joe will too. We'll do our best to get to FPWD in your timescale.

**Comment by jandrieu** [comment]
The issues flagged as FPWD we intend to respond to prior to the FPWD. Only one of those appears to be something we can't actually resolve, #14 We will mark that section as subject to change to give us time to flesh out the question of what to call the system in which a DID is anchored.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2019-11-19-did#section4).

- `RESOLVED:  The DID WG will publish the current Use Cases and Requirements document as a FPWD of the Note, with a publication date of November 28, 2019. Subsequent WDs will be published automatically using Echidna as the editors see fit, following standard group discussion of any PRs.`
<details><summary><i class="differentiate">View the transcript</i></summary>
use cases and requirements fpwd note<br/>
Phil Archer: See UCR candidate FPWD<br/>
Brent Zundel: you all should have received an email with a link to the proposed fpwd of this note<br/>
Manu Sporny: +1 to publish as is…<br/>
Brent Zundel: we have five minutes to hopefully discuss whatever we might need to but the goal of this conversation is to end with a resolution to publish unless there are objections<br/>
… queue up if you would like to add anything<br/>
Dave Longley: +1 to publish<br/>
Ivan Herman: +1<br/>
Phil Archer: +1<br/>
Ivan Herman: before we make a final resolution, a practicality. Two ways of publishing this, we have to decide<br/>
… one is we publish a WD, like we do for a rec, even if it’s clearly saying that it’s not going to become a rec, then at some point in time we publish it as a note<br/>
… the other possibility is we publish a note now which we can update whenever we want<br/>
… it has a different feel to it if you do one or the other, I’m not saying we should do either one in particular, we have a choice and need a clear decision<br/>
Phil Archer: I would say draft because Joe and I have put lots of places in where we say finished or more to come<br/>
… in particular an area we need to add more content is a section for short use cases. there’s a section of more expanded use cases that has been around for a long time, from the CCG<br/>
… but there is a call for more people to provide us with short use cases and without that document is lacking<br/>
… there are open issues that we need to point to it being a draft<br/>
… and content yet to be provided<br/>
Daniel Burnett: +0.000001 draft<br/>
Phil Archer: I prefer something that says this is a draft<br/>
Manu Sporny: are we going to use echidna if the proposal is to do a draft?<br/>
Ivan Herman: personally I defer to the editors on the best way to publish<br/>
… Echidna, yes, as soon as we have the fpwd published, we can’t use echidna for the first round. Then we can set it up<br/>
Joe Andrieu: yes. A draft was our expectation.<br/>
Ivan Herman: if we take the resolution it should also say that editors want to use echidna<br/>
Brent Zundel: typing proposal<br/>
Joe Andrieu: we should also figure out the publication date<br/>
Ivan Herman: yes<br/>
… we have to submit a request for first public draft, I can do it tomorrow, will take a few days, we could aim for the 26th but it doesn’t depend on me<br/>
… I would say the 28th that’s probably very safe. I know it’s US thanksgiving but our webmaster is on the island of Réunion not in the US<br/>
Joe Andrieu: that language sent up red flags about, we still need to have the group chime in if it’s not editorial<br/>
Brent Zundel: any updates to the draft of the note would come through PRs that get discussed by the group<br/>
Proposed resolution: The DID WG will publish the current Use Cases and Requirements document as a FPWD of the Note, with a publication date of November 28, 2019. Subsequent WDs will be published automatically using Echidna as the editors see fit, following standard group discussion of any PRs. (Brent Zundel)<br/>
Manu Sporny: +1<br/>
Ivan Herman: +1<br/>
Ted Thibodeau Jr: +1<br/>
Joe Andrieu: +1<br/>
Phil Archer: +1<br/>
Markus Sabadello: +1<br/>
chris mitre: +1<br/>
Amy Guy: +1<br/>
Dmitri Zagidulin: +1<br/>
Yancy Ribbens: +1<br/>
Kenneth Ebert: +1<br/>
Brent Zundel: any objections?<br/>
Kyle Den Hartog: +1<br/>
Dave Longley: +1<br/>
Resolution #1: The DID WG will publish the current Use Cases and Requirements document as a FPWD of the Note, with a publication date of November 28, 2019. Subsequent WDs will be published automatically using Echidna as the editors see fit, following standard group discussion of any PRs.<br/>
Phil Archer: I’m very keen to hear more use cases. they don’t need to be long<br/>
… particularly ones that are not American<br/>
… this group is dominated by the US<br/>
… some are weird American only things<br/>
… short, brief are good<br/>
Joe Andrieu: in addition to non-US use cases it would be great to see ones that flesh out some of the requirements that drive some of the technical advocacy<br/>
… we don’t have use case coverage for all of the examples brought up in the key conversations<br/>
… the focal ones were written a while ago<br/>
… we don’t have coverage on all the things we want to make happen<br/>
Brent Zundel: we definitely have more work to do, appreciate the editors helping us to move forward<br/>
</details>

**Comment by iherman** [comment]
FPWD request has been issued, see https://github.com/w3c/transitions/issues/188.

**Comment by philarcher** [comment]
Since this question has clearly been answered by the publication of several iterations of the doc, I'm closing this issue.
